version: '3.8'

services:
  backend:
    image: pedrobachaalani1701/trabalho-backend:6.0
    networks:
      - app-net
    deploy:
      replicas: 3 # Define o número de réplicas (contêineres) para o backend
      restart_policy:
        condition: on-failure # Reinicia o contêiner em caso de falha
      update_config:
        parallelism: 1
        delay: 10s
        order: stop-first

  frontend:
    image: pedrobachaalani1701/trabalho-frontend:3.0
    ports:
      - "8080:80"
    networks:
      - app-net
    deploy:
      replicas: 3 # Define o número de réplicas para o frontend
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1
        delay: 10s
        order: stop-first

networks:
  app-net:
    driver: overlay # Define a rede como do tipo 'overlay' para comunicação multi-nó